CREATE TABLE IF NOT EXISTS PRODUCT(
PRODUCT_ID TEXT,
PRODUCT_NAME TEXT,
SUPPLIER_ID TEXT ,
CATEGORY_ID TEXT,
UNIT TEXT,
PRICE REAL
);
INSERT INTO PRODUCT(PRODUCT_ID ,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID ,
UNIT,PRICE )VALUES
("1","CHOCALATE","1","1","1",1.99),
("2","CHOCALATE CAKE","2","2","2",9.99),
("3","COOKIES","3","3","3",0.99),
("4","CUPCAKE","4","4","4",2.99);
SELECT * FROM PRODUCT;
SELECT COUNT(PRODUCT_ID )AS NUMBER_OF_PRODUCT FROM PRODUCT;
SELECT AVG(PRICE) AS AVERAGE_PRICE FROM PRODUCT;
SELECT SUM(PRICE) AS TOTAL_RPICE FROM PRODUCT;
--1)Write a SQL query that finds the number of products--
--2)Write a SQL query that finds the average price of all products.--
--3)Write a SQL query that finds the sum of the price of all products.--

