CREATE TABLE IF NOT EXISTS DEPARTMENT1 (
EMPOLYEE_ID TEXT,
EMPOLYEE TEXT,
SALARY REAL
);
INSERT INTO DEPARTMENT1(EMPOLYEE_ID,EMPOLYEE,SALARY )VALUES
("1","Ali",250.5),
("2","Razan",5500.5),
("3","Ryan",1000.7);
SELECT * FROM DEPARTMENT1;
SELECT MAX(SALARY) AS MAX_PRICE FROM DEPARTMENT1;
SELECT MIN(SALARY) AS MIN_PRICE FROM DEPARTMENT1;